version: "3"
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports: 
    - "27017:27017"
  express-test:
    build: .
    container_name: express-test
    environment:
      - JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'
      - GOOGLE_APP_PASSWORD='${{ secrets.GOOGLE_APP_PASSWORD }}'
      - GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}'
      - GOOGLE_SECRET='${{ secrets.GOOGLE_SECRET }}'
      - GOOGLE_CALLBACK_URL'${{ secrets.GOOGLE_CALLBACK_URL }}'
      - BACKEND_URL='${{ secrets.BACKEND_URL }}'
      - FRONTEND_URL='${{ secrets.FRONTEND_URL }}'
      - MONGO_URI='${{ secrets.MONGO_URI }}'

    depends_on:
      - mongodb

    ports:
      - "80:3000"